### PR TITLE
Export minified React when NODE_ENV is "production"

### LINKED ISSUE #13: Susceptible to changing NODE_ENV
Because this currently loads the development version of React, the outcomes of its `NODE_ENV === 'production'` checks will change based on the changing value of `NODE_ENV`.

Atom 1.8 [updates Atom's ENV](https://github.com/atom/atom/pull/11436) on new invocations from the command line, which often means `NODE_ENV` will change values on subsequent invocations. Changing from Atom's default `NODE_ENV === production` to the common case of an undefined `NODE_ENV` in users' shell environment can lead to crashes like was reported in Nuclide: https://github.com/facebook/nuclide/issues/463

### PR DESCRIPTION
**Pull request by zertosh**
A better way to see this PR is without whitespace: https://github.com/jgebhardt/react-for-atom/compare/with-node-env?expand=1&w=1.

Fixes #13.

Tested this against Nuclide and it's tests.

### CODE REVIEW

File: react-for-atom.js [hunk 1]
```diff
@@ -10,21 +10,37 @@ if (typeof atom.__DO_NOT_ACCESS_React_Singleton === 'undefined') {
...
+    } : {
+      // Perf & TestUtils are not available in production.
+      default: function() { return require('react/dist/react-with-addons.min'); },
+      createFragment: function() { return require('react/dist/react-with-addons.min').addons.createFragment; },
+      CSSTransitionGroup: function() { return require('react/dist/react-with-addons.min').addons.CSSTransitionGroup; },
+      LinkedStateMixin: function() { return require('react/dist/react-with-addons.min').addons.LinkedStateMixin; },
+      // Perf: function() { return require('react/dist/react-with-addons.min').addons.Perf; },
+      PureRenderMixin: function() { return require('react/dist/react-with-addons.min').addons.PureRenderMixin; },
+      React: function() { return require('react/dist/react-with-addons.min'); },
+      ReactDOM: function() { return require('react/dist/react-with-addons.min').__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED; },
```
Comment (ssorallen) [inline react-for-atom.js:37]: 👀 

What does it mean if I give this a thumbs up?

Comment (zertosh) [inline react-for-atom.js:37]: I know :( But maybe if we confess to @zpao, he will have mercy on us.

**Comment by ssorallen** [comment]
Looks good to me. It'd be great to get this merged and into Nuclide before Atom 1.8.

File: react-for-atom.js (hunk 1 above)
Comment (zpao) [inline react-for-atom.js:37]: I won't fire you 😛

File: react-for-atom.js [hunk 2]
```diff
@@ -10,21 +10,37 @@ if (typeof atom.__DO_NOT_ACCESS_React_Singleton === 'undefined') {
...
+      CSSTransitionGroup: function() { return require('react-addons-css-transition-group'); },
+      LinkedStateMixin: function() { return require('react-addons-linked-state-mixin'); },
+      Perf: function() { return require('react-addons-perf'); },
+      PureRenderMixin: function() { return require('react-addons-pure-render-mixin'); },
+      React: function() { return require('react'); },
+      ReactDOM: function() { return require('react-dom'); },
+      ReactDOMServer: function() { return require('react-dom/server'); },
+      shallowCompare: function() { return require('react-addons-shallow-compare'); },
+      TestUtils: function() { return require('react-addons-test-utils'); },
+      TransitionGroup: function() { return require('react-addons-transition-group'); },
```
Comment (zpao) [inline react-for-atom.js:26]: Why not be consistent and use `require('react/dist/react-with-addons')` for all of these ones? I hear that basically nobody is running in dev mode anyway so it probably doesn't matter, but you'd get some speedups here too (cuts out the runtime `NODE_ENV` checks). All of this might not be supported for too much longer if we ever get flat bundling working but you'd have to change everything then anyway.

File: react-for-atom.js [hunk 3]
```diff
@@ -10,21 +10,37 @@ if (typeof atom.__DO_NOT_ACCESS_React_Singleton === 'undefined') {
...
-    PureRenderMixin: function() { return require('react-addons-pure-render-mixin'); },
-    React: function() { return require('react'); },
-    ReactDOM: function() { return require('react-dom'); },
-    ReactDOMServer: function() { return require('react-dom/server'); },
-    shallowCompare: function() { return require('react-addons-shallow-compare'); },
-    TestUtils: function() { return require('react-addons-test-utils'); },
-    TransitionGroup: function() { return require('react-addons-transition-group'); },
-    update: function() { return require('react-addons-update'); },
-  };
+  var exportables = process.env.NODE_ENV !== 'production' ?
```
Comment (ssorallen) [inline react-for-atom.js:13]: Just re-read this... would be nice to invert this case so you don't have to do double negation in your head. `=== ? :` instead of `!== ? :`.

File: react-for-atom.js (hunk 2 above)
Comment (zertosh) [inline react-for-atom.js:26]: Ah yeah, good call. I'll do that in the release when we update to 15.1.0. Thanks!!!

File: react-for-atom.js (hunk 3 above)
Comment (zertosh) [inline react-for-atom.js:13]: This was deliberate to be consistent with react - they express their env checks in terms of `!== "production"`.

Comment (zpao) [inline react-for-atom.js:13]: And I just re-read this and OMG there are way too many lines here for a ternary 😛

Comment (ssorallen) [inline react-for-atom.js:13]: Oh riiiight, `!== "production"`. That is a big ternary though 😮.

Comment (zertosh) [inline react-for-atom.js:13]: Haters.
